# Generated by Django 2.2.10 on 2021-09-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField()),
                ('retailer', models.CharField(choices=[('1st_energy', '1st Energy'), ('agl', 'AGL'), ('alinta_energy', 'Alinta Energy'), ('amber_electrica', 'Amber Electrica'), ('blue_NRG', 'Blue NRG'), ('covaU', 'CovaU'), ('diamond_energy', 'Diamond Energy'), ('discover_energy', 'Discover Energy'), ('dodo_power_and_gas', 'Dodo Power & Gas'), ('elysian_energy', 'Elysian Energy'), ('energy_locals', 'Energy Locals'), ('energyAustralia', 'EnergyAustralia'), ('loBird_energy', 'GloBird Energy'), ('kogan_energy', 'Kogan Energy'), ('lumo_energy', 'Lumo Energy'), ('momentum_energy', 'Momentum Energy'), ('next_business_energy', 'Next Business Energy'), ('origin_energy', 'Origin Energy'), ('OVO_energy', 'OVO Energy'), ('people_energy', 'People Energy'), ('powerclub', 'Powerclub'), ('powerdirect', 'Powerdirect'), ('powershop_australia', 'Powershop Australia'), ('QEnergy_limited', 'QEnergy Limited'), ('reAmped_energy', 'ReAmped Energy'), ('red_energy', 'Red Energy'), ('simply_energy', 'Simply Energy'), ('sumo', 'Sumo'), ('tango_energy', 'Tango Energy')], default='1st_energy', max_length=2)),
                ('interval_data', models.BinaryField()),
                ('manual_input', models.BooleanField()),
                ('electricity_bill', models.BinaryField()),
                ('nphases', models.CharField(choices=[('ONE', '1'), ('THREE', '3'), ('OTHER', 'Other')], default='ONE', max_length=10)),
                ('daily_usage', models.FloatField()),
                ('usage_estimated', models.BooleanField()),
                ('nmi', models.IntegerField()),
                ('meter_a', models.CharField(max_length=100)),
                ('meter_b', models.CharField(max_length=100)),
                ('meter_c', models.CharField(max_length=100)),
                ('service_charge', models.FloatField()),
                ('off_peak_price', models.FloatField()),
                ('on_peak_price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Consumption',
            },
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField()),
                ('has_solar', models.BooleanField()),
                ('year_installed', models.IntegerField()),
                ('previously_approved', models.BooleanField()),
                ('combined_income_value', models.IntegerField()),
                ('combined_income_approved', models.BooleanField()),
                ('property_value', models.IntegerField()),
                ('property_value_approved', models.BooleanField()),
                ('is_eligible', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Eligibility',
            },
        ),
        migrations.CreateModel(
            name='Rebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stcs', models.IntegerField()),
                ('sv_loan', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('loan_requested', models.BooleanField()),
                ('loan_approved', models.BooleanField()),
                ('sv_solar_homes', models.IntegerField()),
                ('solar_homes_amount', models.IntegerField()),
                ('solar_homes_requested', models.BooleanField()),
                ('solar_homes_approved', models.BooleanField()),
                ('sv_battery', models.IntegerField()),
                ('battery_amount', models.IntegerField()),
                ('battery_requested', models.BooleanField()),
                ('battery_approved', models.BooleanField()),
                ('rebate_total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Rebate',
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='house_age',
            field=models.CharField(choices=[('L1Y', '<1'), ('M1YL15', '1 - 15'), ('M15L30', '15 - 30'), ('M30', '30 +')], default='M1YL15', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='roof_material',
            field=models.CharField(choices=[('TIN', 'Tin'), ('TILE', 'Tile'), ('TERRACOTTA', 'Terracotta')], default='TILE', max_length=10),
        ),
    ]
